Add a monkey patch to prevent `NoMethodError` after some parse error in parselet
```
% rspec
.......................................................................................F..F..F...............................................................

/home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:96:in `final_exception': undefined method `cause' for #<Parslet::Cause:0x0055d197064f00> (NoMethodError)
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:99:in `final_exception'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:44:in `formatted_cause'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:39:in `formatted_backtrace'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:70:in `colorized_formatted_backtrace'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:231:in `formatted_message_and_backtrace'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:84:in `fully_formatted_lines'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:76:in `fully_formatted'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:200:in `fully_formatted'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `each'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `each_with_index'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/base_text_formatter.rb:33:in `dump_failures'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:160:in `block in finish'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:175:in `close_after'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:156:in `finish'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:79:in `report'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/yyuu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /home/yyuu/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
        from /home/yyuu/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'
```